<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Autofac" Version="4.9.4" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageVersion Include="Autofac" Version="4.9.3" Condition="'$(TargetFramework)' == 'net6.0'" />
  </ItemGroup>

</Project>
