<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Autofac" Version="4.9.4" />
  </ItemGroup>

  <ItemGroup>
    <GlobalPackageReference Include="AsyncFixer" Version="1.6.0" />
  </ItemGroup>

</Project>
